steps:
- checkout: self
  fetchDepth: 0
  
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'  

- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: DotNetCoreCLI@2  
  displayName: Install NBGV tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv --ignore-failed-sources

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    restoreSolution: '**/$(nugetProjectName)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    externalFeedCredentials: 'CSharkGithubNuget2'

- script: nbgv cloud -a -c
  displayName: Set Version
  
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet version $(NBGV_Version)'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(nugetProjectName)'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'NBGV_Version'
    buildProperties: 'SymbolPackageFormat=snupkg'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'CSharkGithubNuget2'
