steps:
- checkout: self
  fetchDepth: 0
  
- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'  

- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: DotNetCoreCLI@2  
  displayName: Install NBGV tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv --ignore-failed-sources

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    externalFeedCredentials: 'CSharkGithubNuget2'

- script: nbgv cloud -a -c
  displayName: Set Version

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  displayName: Nuget Pack
  inputs:
    command: 'custom' 
    arguments: 'pack $(packageName).nuspec -Version $(GitBuildVersion)'

- script: nuget push $(Build.ArtifactStagingDirectory)\..\**\$(packageName).$(GitBuildVersion).nupkg -Source mako-iot -ApiKey $(githubToken)
  displayName: nuget push