steps:
- checkout: self
  fetchDepth: 0
  
- task: NuGetToolInstaller@1
  displayName: Install NuGet
  
- task: DotNetCoreCLI@2  
  displayName: Install NBGV tool
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv --ignore-failed-sources

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  retryCountOnTaskFailure: 3
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- script: nbgv cloud -a -c
  displayName: Set Version
  
- task: DotNetCoreCLI@2
  displayName: 'Pack NuGet version $(GitBuildVersion)'
  inputs:
    command: 'pack'
    packagesToPack: '**/$(nugetProjectName)'
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GitBuildVersion'
    buildProperties: 'SymbolPackageFormat=snupkg'

- script: nuget push $(Build.ArtifactStagingDirectory)/**/*.nupkg -Source mako-iot -ApiKey $(nugetToken)
  displayName: nuget push
