steps:
- checkout: self
  fetchDepth: 0
         
- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  retryCountOnTaskFailure: 3
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'
          
- task: DotNetCoreCLI@2
  displayName: 'Tests Unit'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    projects: |
      $(System.DefaultWorkingDirectory)\Tests\**\*Test*.csproj
      **/*Tests.Unit.csproj
      !**/obj/**
      !**/bin/**/ref/**         