trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - .gitignore
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE.md
      - README.md
      - NuGet.Config
      - ./*.yml

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  runSettingsFile: 'Tests\MakoIoT.Device.Utilities.ICalParser.Test\nano.runsettings'

steps:
- checkout: self
  fetchDepth: 0

- task: InstallnFBuildComponents@1
  displayName: Install nanoFramework MSBuild components
  env:
    GITHUB_TOKEN: $(github_nuget_token)

- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    externalFeedCredentials: 'CSharkGithubNuget'

- task: VSBuild@1
  displayName: Build solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArchitecture: x64

- task: VSTest@2
  displayName: Run tests
  continueOnError: false
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      $(System.DefaultWorkingDirectory)\Tests\**\NFUnitTest.dll
      $(System.DefaultWorkingDirectory)\Tests\**\*Test*.dll
      !**\DeviceTest.dll
      !**\obj\**
      !**\TestAdapter\**
      !**\NFUnitTest_DummyAdapter\**
      !**\nanoFramework.TestFramework\**    
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    runSettingsFile: '$(System.DefaultWorkingDirectory)\$(runSettingsFile)'
