steps:
- checkout: self
  fetchDepth: 0

- task: UseDotNet@2
  displayName: Use .NET 6.0
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
          
- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: NuGetCommand@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'config'
    nugetConfigPath: 'nuget.config'
    externalFeedCredentials: 'CSharkGithubNuget2'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(solution)'
    configuration: '$(buildConfiguration)'
          
- task: DotNetCoreCLI@2
  displayName: 'Tests Unit'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    publishTestResults: true
    projects: |
      $(System.DefaultWorkingDirectory)\Tests\**\*Test*.csproj
      **/*Tests.Unit.csproj
      !**/obj/**
      !**/bin/**/ref/**         