# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- group: mako-iot-github
- name: Organization
  value: 'CShark-Hub'
- name: GitHubUser
  value: 'nanodu'
- name: NuGetSource
  value: 'https://nuget.pkg.github.com/CShark-Hub/index.json'
- name: NuGetFeedName
  value: 'mako-iot'

pool:
  vmImage: windows-latest
 
steps:
- task: PowerShell@2
  displayName: Run update script
  inputs:
    filePath: 'scripts/updateDependencies.ps1'
    arguments: '-organization $(Organization) -gitHubToken $(githubToken) -gitHubUser $(GitHubUser)'
    failOnStderr: true
    showWarnings: true
