# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
- group: mako-iot-github
- name: Organization
  value: 'CShark-Hub'
- name: GitHubUser
  value: 'torbacz'
- name: NuGetSource
  value: 'https://nuget.pkg.github.com/CShark-Hub/index.json'
- name: NuGetFeedName
  value: 'CsharkMakoIoT'

pool:
  vmImage: ubuntu-latest
 
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: dotnet nuget update source $(NuGetFeedName) --source $(NuGetSource) --username USERNAME --password $(githubToken) --store-password-in-clear-text

- task: PowerShell@2
  displayName: Run update script
  inputs:
    filePath: 'scripts/updateDependencies.ps1'
    arguments: '-organization $(Organization) -gitHubToken $(githubToken) -gitHubUser $(GitHubUser)'
    failOnStderr: true
    showWarnings: true
